### ISSUE TITLE
[Translation]Simplified Chinese Update/简体中文更新

### ISSUE THREAD

**Issue by qiuzilu** [Defective4/Another-Minecraft-Chat-Client#10]
[CN.zip](https://github.com/Defective4/Another-Minecraft-Chat-Client/files/8305106/CN.zip)
Hello! @Defective4 
I'm sorry that I haven't translated for so long because I have to go to school...

**Comment by qiuzilu** [comment]
Also ,I still haven't finished translating. . .

**Comment by Defective4** [comment]
Thank you! I will review your translation in my spare time and I will update it in the next release.

**Comment by Defective4** [comment]
Added in [release 1.6.0](https://github.com/Defective4/Another-Minecraft-Chat-Client/releases/tag/v1.6.0)
