### ISSUE TITLE
[Feature] Personally suggested features needed

### ISSUE THREAD

**Issue by xiaoliang2012** [Defective4/Another-Minecraft-Chat-Client#11]
You can add an automatic fishing feature！
Anyway, it's best to do something!
you can refer to：https://github.com/BaiMeow/FishBot
thanks

**Comment by Defective4** [comment]
I will try to add id as soon as I manage to receive chunks from server.
Thank you for your suggestion!

**Comment by Picadoo** [comment]
May anther one called  Minecraft Console Client help you . I would appreciate it if you could add auto attack to kill mobs.

**Comment by Defective4** [comment]
It's a good idea. I should be able to add this in one of the upcoming updates

**Comment by Picadoo** [comment]
Thank you! It must help me a lot. I play in a sever which needs us to kill a large amount of mobs.

**Comment by xiaoliang2012** [comment]
You can add a proxy IP function

**Comment by Defective4** [comment]
> You can add a proxy IP function

No problem, I will add this in the next release

**Comment by xiaoliang2012** [comment]
“Attacking nearby entities”  It doesn't seem to have come true

**Comment by Defective4** [comment]
> “Attacking nearby entities”  It doesn't seem to have come true

Please be patient, I am still working on it although I am pretty busy lately. Nonetheless I will add it as soon as I can, as I promised

**Comment by xiaoliang2012** [comment]
It's best to have a switch that can be turned on or off
I didn't mean to urge
I'm very sorry

**Comment by Defective4** [comment]
It's fine. I can understand since I am taking so long to implement these features.
I am sorry for the inconvenience.

**Comment by Defective4** [comment]
@xiaoliang2012 sorry for the long wait, but in the latest update most of features you requested are finally available!
I still can't add Fishing Bot though and I don't think it will be possible anytime soon, so I will close this issue for now.
