### ISSUE TITLE
Some accounts cannot log in normally

### ISSUE THREAD

**Issue by ShermanYawa** [Defective4/Another-Minecraft-Chat-Client#12]
Why do I use this on-hook software to enter the server with some accounts, and some accounts can not enter at first, but after a period of time, it will display: EncoderException : java.lang.NullPointerException @ io.netty.handler.codec.MessageToByteEncoder:125

**Comment by Defective4** [comment]
Do you experience this issue on all servers you try to enter or only on a specific one?

**Comment by Defective4** [comment]
Closing, because there is lack of information regarding this issue.

**Comment by Hyphonic** [comment]
Im having the same issue when i connect with my alt account (Mojang) to any server
I either get:
![Type 1](https://user-images.githubusercontent.com/69310714/187077514-5b067cd4-881b-4757-8690-a6735f4bdc4c.png)
or:
![Type 2](https://user-images.githubusercontent.com/69310714/187077516-90ebffb5-2f63-443b-ba7d-0651c7835420.png)

**Comment by Defective4** [comment]
Closing as Mojang authentication is no longer supported and it's waiting for removal. (#24)
