### ISSUE TITLE
AVG Thinks it a virus

### ISSUE THREAD

**Issue by catdogmat** [Defective4/Another-Minecraft-Chat-Client#2]
**Describe the bug**
AVG Thinks it a virus IDP.Generic

**To Reproduce**
Steps to reproduce the behavior
1 Download AVG
2 Download App
3 Open App
4 Virus Warning

**Expected behavior**
It works

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 7]
 - Version [e.g. 1.2.1]

**Additional context**

**Comment by Defective4** [comment]
App's exe file is built using Launch4j, which often creates false positives. 
The file itself is safe to execute, but if your antivirus prevents you from opening it, try downloading the .jar version of application.

**Comment by Defective4** [comment]
Resolved in [release 1.5.5](https://github.com/Defective4/Another-Minecraft-Chat-Client/releases/tag/1.5.5)
