### ISSUE TITLE
[Translation]Simplified Chinese Update/简体中文

### ISSUE THREAD

**Issue by xiaoliang2012** [Defective4/Another-Minecraft-Chat-Client#26]
[CN.zip](https://github.com/Defective4/Another-Minecraft-Chat-Client/files/10431656/CN.zip)
Hello! @Defective4
I translated for the first time. There may be errors

**Comment by qiuzilu** [comment]
![X8J(LBW8BGMSUTQBY(917%Q](https://user-images.githubusercontent.com/64822124/212890668-f3c3bbd6-7c0a-496b-be01-ef2548581c67.jpg)

**Comment by Defective4** [comment]
Thank you @xiaoliang2012!
I will review your translation and if everything goes well I will add it in the next release!

**Comment by xiaoliang2012** [comment]
Thank you

**Comment by Defective4** [comment]
Your translation is now available in the new [release v1.10.0](https://github.com/Defective4/Another-Minecraft-Chat-Client/releases/tag/v1.10.0).
Thank you very much for your contribution, I really appreciate it!
