### ISSUE TITLE
TheAltening and Offline only

### ISSUE THREAD

**Issue by yayy80** [Defective4/Another-Minecraft-Chat-Client#30]
**Describe the bug**
It only accepts TheAltening (premium account hosting), and offline.

**To Reproduce**
Going to the connect, clicking drop down for authentication type, and seeing no Microsoft login

**Expected behavior**
Seeing Microsoft login.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version latest

**Comment by Defective4** [comment]
Microsoft authentication is mentioned as Work In Progress in #22 as well as #24.
It's safe to consider that this issue is a duplicate.

**Comment by Defective4** [comment]
@yayy80 The Microsoft authentication is available as of latest (v1.11.0) release.
