### ISSUE TITLE
[Translation]Simplified Chinese/简体中文

### ISSUE THREAD

**Issue by qiuzilu** [Defective4/Another-Minecraft-Chat-Client#5]
Simplified Chinese ,and not a full translation.

[CN.properties.zip](https://github.com/Defective4/Another-Minecraft-Chat-Client/files/8020368/CN.properties.zip)

**Comment by qiuzilu** [comment]
还没有翻译完整，大概翻译了1/3

**Comment by qiuzilu** [comment]
I have done the basic translation , so please include it in next release ! 
THANKS!

**Comment by qiuzilu** [comment]
This is the Minecraft 1.18.1 Simplified Chinese language pack.
[cn.lang.zip](https://github.com/Defective4/Another-Minecraft-Chat-Client/files/8030406/cn.lang.zip)
@Defective4

**Comment by Defective4** [comment]
I have reviewed your translation and it will be included in the next release.
Again, thank you very much for your contribution!

**Comment by Defective4** [comment]
Your translation was added in [release 1.5.4](https://github.com/Defective4/Another-Minecraft-Chat-Client/releases/tag/v1.5.4).
Once again, thank you for making Another Minecraft Chat Client better!
If you ever want to modify/improve your translation, or anything in general, feel free to open a new issue.
