### ISSUE TITLE
Reprint application

### ISSUE THREAD

**Issue by qiuzilu** [Defective4/Another-Minecraft-Chat-Client#6]
(I had already sent you an e-mail before I write this issues , but I'm worried maybe you don't check email very often ,So I'm here to apply again）

Cześć！
I am a Chinese Minecraft player . I stumbled across your build on github " Another-Minecraft-Chat-Client ". It caught my eye but there are still many imperfections . Although I don't know how to build a program , but I am truly want to play a part to make it better . 
SO.....
Could I advertise this wonderful Minecraft Chat Client to MCBBS(https://www.mcbbs.net)？ It is the largest Minecraft forum in China . There are many wonderful and helpful players . I think we can work together to make " Another-Minecraft-Chat-Client " become better .

**Comment by Defective4** [comment]
Hi @qiuzilu
I'm glad you're interested in my little project.
I realize that my program is not perfect, so I'm glad you want to help me!
Feel free to advertise my "chat client" if you like. I would be very grateful for that!

Also, sorry that I did not reply to your e-mail, I check my correspondence only once every few days, so I definitely prefer to receive messages via GitHub

**Comment by qiuzilu** [comment]
Hello! @Defective4 
I've finished！！！
Hope it will attract more developer.
https://www.mcbbs.net/thread-1303395-1-1.html

**Comment by qiuzilu** [comment]
If you have any dissatisfaction, please bring it up，I will make changes .
