### ISSUE TITLE
[Feature] Can you support Forge?

### ISSUE THREAD

**Issue by Baikele** [Defective4/Another-Minecraft-Chat-Client#8]
**Is your feature request related to a problem? Please describe.**
Can you support Forge?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Defective4** [comment]
Yes, I am currently preparing to add Forge support, but I don't know when it will be finished.

**Comment by Defective4** [comment]
Forge for Minecraft 1.8 - 1.12.2 is now supported in [release 1.6.0](https://github.com/Defective4/Another-Minecraft-Chat-Client/releases/tag/v1.6.0)

**Comment by Baikele** [comment]
> 

Do I need to put mods in the mods folder? Or how?

**Comment by Defective4** [comment]
You don't need to do anything @Baikele. You can join a Forge server just like any other. Just make sure you are using the latest version of AMCC
