### ISSUE TITLE
It seems that bc server is not supported![Feature] 

### ISSUE THREAD

**Issue by xiaoliang2012** [Defective4/Another-Minecraft-Chat-Client#9]
BC server will be disconnected when it reaches the sub-server!

**Comment by xiaoliang2012** [comment]
The server jumps to another server and the connection fails! 
Hint: java.io.IOException: No such packet: ServerPlayerListItemPacket

**Comment by Defective4** [comment]
Can you give me the IP and Minecraft version you are using? This will help me study the circumstances under which it happens.

**Comment by xiaoliang2012** [comment]
Server address: www.mctop1.com cn:17075
Version: 1.18.1
Support versions 1.8 to 1.18 X enter the game

**Comment by xiaoliang2012** [comment]
You can log in to the server. An error will be reported when transferring to another group server

**Comment by Defective4** [comment]
Thank you, i will look into this issue as soon as possible and hopefully I will come up with a solution.

**Comment by xiaoliang2012** [comment]
thank you!!!

**Comment by xiaoliang2012** [comment]
I think the problem is caused by the different versions of the BC server, it's just my guess

**Comment by Defective4** [comment]
Your issue has been fixed in [release 1.5.5](https://github.com/Defective4/Another-Minecraft-Chat-Client/releases/tag/1.5.5).
